# Identifico el proyecto dentro de SonarQube con una clave única.
# Esta clave permite que SonarQube distinga este proyecto de otros.
sonar.projectKey=gestor-cursos-react

# Nombre visible del proyecto en el panel de SonarQube.
# Es la etiqueta que aparecerá en la interfaz.
sonar.projectName=Gestor Cursos React

# Versión del proyecto que estoy analizando.
# Me sirve para llevar control de versiones en los reportes de calidad.
sonar.projectVersion=1.0

# Indico la carpeta donde está mi código fuente real.
# SonarQube analizará únicamente los archivos dentro de "src".
sonar.sources=src

# Especifico qué carpetas deben excluirse del análisis.
# node_modules contiene dependencias externas y dist contiene archivos generados.
# Ninguna de estas carpetas debe ser analizada.
sonar.exclusions=node_modules/**,dist/**

# Defino la codificación de caracteres del proyecto.
# UTF-8 evita problemas con acentos, ñ y caracteres especiales.
sonar.sourceEncoding=UTF-8

# URL donde se alojará la prueba realizada por el Docker.
sonar.host.url=http://localhost:9000